config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :schools, controllers: {
    sessions: 'public/schools/sessions',
    passwords: 'public/schools/passwords',
    registrations: 'public/schools/registrations'
  }

  devise_for :players, controllers: {
    sessions: 'public/players/sessions',
    passwords: 'public/players/passwords',
    registrations: 'public/players/registrations'
  }

  namespace :admin do
    resources :players, only: [:index, :edit, :update]
    resources :schools, only: [:index, :edit, :update]
  end

  scope module: :public do
    
    # 退会確認画面&論理削除用のルーティング
    get 'unsubscribe_check' => 'players#unsubscribe_check', as: 'unsubscribe_check'
    patch 'players/unsubscribe' => 'players#unsubscribe', as: 'unsubscribe'
    get 'unsubscribe_confirm' => 'schools#unsubscribe_confirm', as: 'unsubscribe_confirm'
    patch 'schools/unsubscribe' => 'schools#unsubscribe', as: 'unsubscribe_school'

    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :players, only: [:show, :edit, :update] do
      post "likes" => "likes#create", as: "likes"
      delete "like" => "likes#destroy", as: "like"
    end

    resources :schools do
      get '/likes_players' => 'likes#like'
    end

    resources :rooms, only: [:create,:show, :index] do
      resources :messages, only: [:create]
    end

      get '/searches' => 'schools/searches#search'
      get '/searches/result' => 'schools/searches#result'

  end

end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :liked_schools, through: :likes, source: :school
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :player_image

  enum grade: {
    中学1年:1,中学2年:2,中学3年:3
  }

  enum base: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

  # deviseで用意されている処理に対して
  # player_status が true (つまり退会している状態) なのかを
  # 調べて、退会してなければログインする処理を付け足している
  def active_for_authentication?
    super && (self.player_status == false)
  end

  def self.search(params)
    #if params[:name].blank? && params[:grade].blank? && params[:base].blank? && params[:school].blank? && params[:enrollment].blank?
      #Player.all
    #else
      #Player.where('name LIKE ? AND grade LIKE ? AND base LIKE ? AND school LIKE ? AND enrollment LIKE ?', "%#{params[:name]}%", params[:grade].to_i, params[:base].to_i, "%#{params[:school]}%", "%#{params[:enrollment]}%")
      #byebug
      # Player.where("name LIKE ?", "#{params[:name]}").where("")
      #players = Player.where("name LIKE ?", "#{params[:name]}")
      #players = players.where("grade LIKE ?", "#{params[:grade]}") unless params[:grade] == ""
      #players = Player.where('name LIKE ? AND school LIKE ? AND enrollment LIKE ?', "%#{params[:name]}%", "%#{params[:school]}%", "%#{params[:enrollment]}%")
      players = Player.all
      players = players.where('name LIKE ?', "%#{params[:name]}%" ) unless params[:name] == ""
      players = players.where('school LIKE ?', "%#{params[:school]}%" ) unless params[:shool] == ""
      players = players.where('enrollment LIKE ?', "%#{params[:enrollment]}%" ) unless params[:enrollment] == ""
      players = players.where(grade: params[:grade].to_i) unless params[:grade] == ""
      players = players.where(base: params[:base].to_i) unless params[:base] == ""
      players
    #end
  end



end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(member_params)
      flash[:success] = "登録情報を変更しました"
      redirect_to admin_players_path
    else
      render :edit
    end
  end



  private

  def member_params
    params.require(:player).permit(:name, :school, :enrollment, :grade, :base, :player_status)
  end


end

app/helpers/admins/players_helper.rb
module Admins::PlayersHelper
end

app/helpers/player/members_helper.rb
module Player::MembersHelper
end

app/helpers/players/posts_helper.rb
module Players::PostsHelper
end

app/views/admin/players/edit.html.erb
<div class="container">
  <h2 class="page-title">-<%= @player.name %>-</h2>
  <%= form_with model: @player, url: admin_player_path, method: :patch, local: true do |f| %>
  <p>選手ID <%= @player.id %></p>
  <table class="table table-bordered mt-3">
    <tbody>
      <tr>
        <td>
          <%= f.label "選手名" %>
          <%= f.text_field :name %>
        </td>
        <td>
          <%= f.label "e-mail" %>
          <%= f.text_field :email %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label "在籍校" %>
          <%= f.text_field :school %>
        </td>
        <td>
          <%= f.label "在籍チーム" %>
          <%= f.text_field :enrollment %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label "学年" %>
          <%= f.select :grade, options_for_select(Player.grades.keys, selected: @player.grade), {prompt: "選択してください"} %>
        </td>
        <td>
          <%= f.label "活動拠点" %>
          <%= f.select :base, options_for_select(Player.bases.keys, selected: @player.base), {prompt: "選択してください"} %>
        </td>
      </tr>
    </tbody>
  </table>
  
  <div class="form-group col-md-12">
    <%= f.label "選手ステータス", class: "col-md-4 control-label" %>
    <%= f.radio_button :player_status, false %>
  　<%= f.label :player_status, "有効", {value: :false, style: "display: inline-block;"} %>
  　<%= f.radio_button :player_status, true %>
  　<%= f.label :player_status, "退会", {value: :true, style: "display: inline-block;"} %>
  </div>

  <div class="actions col-md-12">
    <%= link_to "保存せずに戻る", admin_players_path, class: "glyphicon glyphicon-home btn btn-info" %>
    <%= f.submit "編集内容を保存する",class: "btn btn-primary save col-xs-6" %>
  </div>

  <% end %>


</div>

app/views/admin/players/index.html.erb
<div class="container">
  <h2 class="page-title">-Players list-</h2>
  <table class="table text-center mt-3">
    <thead>
      <tr>
        <th>選手ID</th>
        <th>選手名</th>
        <th>学年</th>
        <th>学校</th>
        <th>在籍チーム</th>
        <th>活動拠点</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <% @players.each do |player| %>
    <tbody>
      <tr>
        <td><%= player.id %></td>
        <td><%= link_to player.name, edit_admin_player_path(player.id) %></td>
        <td><%= player.grade %></td>
        <td><%= player.school %></td>
        <td><%= player.enrollment %></td>
        <td><%= player.base %></td>
        <td>
          <% if player.player_status == true %>
            <p><i class="fas fa-bullseye blue"></i>退会済</p>
          <% else %>
            <p><i class="fas fa-bullseye red"></i>有効</p>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>


</div>