config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :schools, controllers: {
    sessions: 'public/schools/sessions',
    passwords: 'public/schools/passwords',
    registrations: 'public/schools/registrations'
  }

  devise_for :players, controllers: {
    sessions: 'public/players/sessions',
    passwords: 'public/players/passwords',
    registrations: 'public/players/registrations'
  }

  namespace :admin do
    resources :players, only: [:index, :edit, :update]
    resources :schools, only: [:index, :edit, :update]
  end

  scope module: :public do
    
    # 退会確認画面&論理削除用のルーティング
    get 'unsubscribe_check' => 'players#unsubscribe_check', as: 'unsubscribe_check'
    patch 'players/unsubscribe' => 'players#unsubscribe', as: 'unsubscribe'
    get 'unsubscribe_confirm' => 'schools#unsubscribe_confirm', as: 'unsubscribe_confirm'
    patch 'schools/unsubscribe' => 'schools#unsubscribe', as: 'unsubscribe_school'

    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :players, only: [:show, :edit, :update] do
      post "likes" => "likes#create", as: "likes"
      delete "like" => "likes#destroy", as: "like"
    end

    resources :schools do
      get '/likes_players' => 'likes#like'
    end

    resources :rooms, only: [:create,:show, :index] do
      resources :messages, only: [:create]
    end

      get '/searches' => 'schools/searches#search'
      get '/searches/result' => 'schools/searches#result'

  end

end

app/models/school.rb
class School < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes, dependent: :destroy
  has_many :liked_players, through: :likes, source: :player
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def already_liked?(player)
    self.likes.exists?(player_id: player.id)
  end

  attachment :high_school_image

  enum dormitory: {
    有:1,無:2
  }

  # deviseで用意されている処理に対して
  # player_status が true (つまり退会している状態) なのかを
  # 調べて、退会してなければログインする処理を付け足している
  def active_for_authentication?
    super && (self.school_status == false)
  end


end

app/controllers/admin/schools_controller.rb
class Admin::SchoolsController < ApplicationController
  def index
    @schools = School.all
  end

  def edit
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])
    if @school.update(team_params)
      flash[:success] = "登録情報を変更しました"
      redirect_to admin_schools_path
    else
      render :edit
    end
  end



  private

  def team_params
    params.require(:school).permit(:high_school_name, :manager_name, :address, :email, :spring_koshien_times, :summer_koshien_times, :dormitory, :school_status)
  end


end

app/helpers/admins/schools_helper.rb
module Admins::SchoolsHelper
end

app/helpers/school/teams_helper.rb
module School::TeamsHelper
end

app/views/admin/schools/edit.html.erb
<div class="container">
  <h2 class="page-title">-<%= @school.high_school_name %>-</h2>
  <%= form_with model: @school, url: admin_school_path, method: :patch, local: true do |f| %>
  <p>学校ID<%= @school.id %></p>
  <table class="table table-bordered mt-3">
    <tbody>
      <tr>
        <td>
          <%= f.label "学校名" %>
          <%= f.text_field :high_school_name %>
        </td>
        <td>
          <%= f.label "e-mail" %>
          <%= f.text_field :email %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label "監督" %>
          <%= f.text_field :manager_name %>
        </td>
        <td>
          <%= f.label "所在地" %>
          <%= f.text_field :address %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label "寮" %>
          <%= f.select :dormitory, options_for_select(School.dormitories.keys ,selected: @school.dormitory), {prompt: "選択してください"}  %>
        </td>
        <td>
          <%= f.label "甲子園出場回数" %>
          春 <%= f.text_field :spring_koshien_times, :size=>"3" %> 夏 <%= f.text_field :summer_koshien_times, :size=>"3" %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="form-group col-md-12">
    <%= f.label "学校ステータス", class: "col-md-4 control-label" %>
    <%= f.radio_button :school_status, false %>
  　<%= f.label :school_status, "有効", {value: :false, style: "display: inline-block;"} %>
  　<%= f.radio_button :school_status, true %>
  　<%= f.label :school_status, "退会", {value: :true, style: "display: inline-block;"} %>
  </div>

  <div class="actions col-md-12">
    <%= link_to "保存せずに戻る", admin_schools_path, class: "glyphicon glyphicon-home btn btn-info" %>
    <%= f.submit "編集内容を保存する",class: "btn btn-primary save col-xs-6" %>
  </div>

  <% end %>


</div>

app/views/admin/schools/index.html.erb
<div class="container">
  <h2 class="page-title">-School list-</h2>
  <table class="table text-center mt-3">
    <thead>
      <tr>
        <th>学校ID</th>
        <th>学校</th>
        <th>監督</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <% @schools.each do |school| %>
    <tbody>
      <tr>
        <td><%= school.id %></td>
        <td><%= link_to school.high_school_name, edit_admin_school_path(school.id) %></td>
        <td><%= school.manager_name %></td>
        <td>
          <% if school.school_status == true %>
            <p><i class="fas fa-bullseye blue"></i>退会</p>
          <% else %>
            <p><i class="fas fa-bullseye red"></i>有効</p>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>


</div>