config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :schools, controllers: {
    sessions: 'public/schools/sessions',
    passwords: 'public/schools/passwords',
    registrations: 'public/schools/registrations'
  }

  devise_for :players, controllers: {
    sessions: 'public/players/sessions',
    passwords: 'public/players/passwords',
    registrations: 'public/players/registrations'
  }

  namespace :admin do
    resources :players, only: [:index, :edit, :update]
    resources :schools, only: [:index, :edit, :update]
  end

  scope module: :public do
    
    # 退会確認画面&論理削除用のルーティング
    get 'unsubscribe_check' => 'players#unsubscribe_check', as: 'unsubscribe_check'
    patch 'players/unsubscribe' => 'players#unsubscribe', as: 'unsubscribe'
    get 'unsubscribe_confirm' => 'schools#unsubscribe_confirm', as: 'unsubscribe_confirm'
    patch 'schools/unsubscribe' => 'schools#unsubscribe', as: 'unsubscribe_school'

    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :players, only: [:show, :edit, :update] do
      post "likes" => "likes#create", as: "likes"
      delete "like" => "likes#destroy", as: "like"
    end

    resources :schools do
      get '/likes_players' => 'likes#like'
    end

    resources :rooms, only: [:create,:show, :index] do
      resources :messages, only: [:create]
    end

      get '/searches' => 'schools/searches#search'
      get '/searches/result' => 'schools/searches#result'

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  
  belongs_to :player, optional: true
  belongs_to :school, optional: true
  belongs_to :room
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :player
  belongs_to :school
  validates_uniqueness_of :player_id, scope: :school_id
end

app/models/message.rb
class Message < ApplicationRecord
  
  validates :content, presence: true
  belongs_to :player, optional: true
  belongs_to :school, optional: true
  belongs_to :room
  
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :liked_schools, through: :likes, source: :school
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :player_image

  enum grade: {
    中学1年:1,中学2年:2,中学3年:3
  }

  enum base: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

  # deviseで用意されている処理に対して
  # player_status が true (つまり退会している状態) なのかを
  # 調べて、退会してなければログインする処理を付け足している
  def active_for_authentication?
    super && (self.player_status == false)
  end

  def self.search(params)
    #if params[:name].blank? && params[:grade].blank? && params[:base].blank? && params[:school].blank? && params[:enrollment].blank?
      #Player.all
    #else
      #Player.where('name LIKE ? AND grade LIKE ? AND base LIKE ? AND school LIKE ? AND enrollment LIKE ?', "%#{params[:name]}%", params[:grade].to_i, params[:base].to_i, "%#{params[:school]}%", "%#{params[:enrollment]}%")
      #byebug
      # Player.where("name LIKE ?", "#{params[:name]}").where("")
      #players = Player.where("name LIKE ?", "#{params[:name]}")
      #players = players.where("grade LIKE ?", "#{params[:grade]}") unless params[:grade] == ""
      #players = Player.where('name LIKE ? AND school LIKE ? AND enrollment LIKE ?', "%#{params[:name]}%", "%#{params[:school]}%", "%#{params[:enrollment]}%")
      players = Player.all
      players = players.where('name LIKE ?', "%#{params[:name]}%" ) unless params[:name] == ""
      players = players.where('school LIKE ?', "%#{params[:school]}%" ) unless params[:shool] == ""
      players = players.where('enrollment LIKE ?', "%#{params[:enrollment]}%" ) unless params[:enrollment] == ""
      players = players.where(grade: params[:grade].to_i) unless params[:grade] == ""
      players = players.where(base: params[:base].to_i) unless params[:base] == ""
      players
    #end
  end



end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :player
  attachment :image

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

end

app/models/school.rb
class School < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes, dependent: :destroy
  has_many :liked_players, through: :likes, source: :player
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def already_liked?(player)
    self.likes.exists?(player_id: player.id)
  end

  attachment :high_school_image

  enum dormitory: {
    有:1,無:2
  }

  # deviseで用意されている処理に対して
  # player_status が true (つまり退会している状態) なのかを
  # 調べて、退会してなければログインする処理を付け足している
  def active_for_authentication?
    super && (self.school_status == false)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_rooms

  def after_sign_up_path_for(resource)
    case resource
    when Admin
      root_path
    when Player
      players_member_path(current_player.id)
    when School
      schools_team_path(current_school.id)
    end
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_players_path
    when Player
      player_path(resource)
    when School
      school_path(resource)
    end
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :grade, :school, :enrollment, :base, :high_school_name, :manager_name, :spring_koshien_times, :summer_koshien_times, :address, :dormitory])
  end

  def set_rooms
    @entry_all = nil
    if school_signed_in?
      @entry_all = Entry.where(school_id: current_school.id)
    elsif player_signed_in?
      @entry_all = Entry.where(player_id: current_player.id)
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admins/players_helper.rb
module Admins::PlayersHelper
end

app/helpers/admins/schools_helper.rb
module Admins::SchoolsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/common/serches_helper.rb
module Common::SerchesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/player/members_helper.rb
module Player::MembersHelper
end

app/helpers/players/posts_helper.rb
module Players::PostsHelper
end

app/helpers/school/teams_helper.rb
module School::TeamsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ballpark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="footerFixed">
      <header>
        <nav class="navbar navbar-expand-md navbar-light bg-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand pl-2" href="/">Ballpark</a>

          <div class="collapse navbar-collapse justify-content-around" id="navbarNav4">

            <ul class="navbar-nav ml-auto">

              <% if admin_signed_in? %>
                <li class="header-name">管理者ログイン</li>
                <li class="nav"><%= link_to "選手一覧", admin_players_path, class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to "学校一覧", admin_schools_path, class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link navbar-light" %></li>
              <% end %>

              <% if player_signed_in? %>
                <li class="header-name">
                  <%= current_player.name %>でログイン
                </li>
                <li class="nav"><%= link_to '選手マイページ', player_path(current_player.id), class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to '新規投稿', new_post_path, class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to 'メッセージ', rooms_path, class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to "ログアウト", destroy_player_session_path, method: :delete, class: "nav-link navbar-light" %></li>
              <% end %>

              <% if school_signed_in? %>
                <li class="header-name">
                  <%= current_school.high_school_name %>でログイン
                </li>
                <li class="nav"><%= link_to '学校マイページ', school_path(current_school.id), class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to '選手検索', searches_path, class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to 'ピックアップリスト', school_likes_players_path(current_school.id), class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to 'メッセージ', rooms_path, class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to "ログアウト", destroy_school_session_path, method: :delete, class: "nav-link navbar-light" %></li>
              <% end %>

              <% if school_signed_in? == false && player_signed_in? == false && admin_signed_in? == false %>
                <li class="nav"><%= link_to "選手新規登録", new_player_registration_path, class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to "選手ログイン", new_player_session_path, class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to "学校新規登録", new_school_registration_path, class: "nav-link navbar-light" %></li>
                <li class="nav"><%= link_to "学校ログイン", new_school_session_path, class: "nav-link navbar-light" %></li>
              <% end %>

            </ul>
        </nav>
      </header>
      <main>
      <%= yield %>
      </main>
      <footer>
        <p>Copyright © Ballpark All Rights Reserved.</p>
      </footer>
    </div>
  </body>
</html>

app/views/partial/_unsubscribe.html.erb
<div class="container">
  <div>
    <h2 class="page-title">本当に退会しますか？</h2>
    <div class="last-text">
      退会すると、登録情報や</br>
      これまでの投稿履歴が閲覧できなくなります。</br>
      退会する場合は、『退会する』をクリックしてください。
    </div>
    <div class="last-btn d-flex justify-content-center">
      <%= link_to '退会しない', back_url, class:"btn btn-primary w-25 mr-5" %>
      <%= link_to "退会する", go_unsubscribe_url, method: :patch, class:"btn btn-danger w-25 ml-5" %>
    </div>
  </div>
</div>